# coding: utf-8

"""
    API 2.0

    Early release of version 2.0 of the Vend API.

    OpenAPI spec version: 2.0
    Contact: api@vendhq.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..api_client import ApiClient


class ProductImagesApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete_product_image_by_id(self, product_image_id, **kwargs):
        """
        Delete a product_image
        Deletes the product_image with the requested ID.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.delete_product_image_by_id(product_image_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str product_image_id:  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.delete_product_image_by_id_with_http_info(product_image_id, **kwargs)
        else:
            (data) = self.delete_product_image_by_id_with_http_info(product_image_id, **kwargs)
            return data

    def delete_product_image_by_id_with_http_info(self, product_image_id, **kwargs):
        """
        Delete a product_image
        Deletes the product_image with the requested ID.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.delete_product_image_by_id_with_http_info(product_image_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str product_image_id:  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['product_image_id']
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_product_image_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'product_image_id' is set
        if ('product_image_id' not in params) or (params['product_image_id'] is None):
            raise ValueError("Missing the required parameter `product_image_id` when calling `delete_product_image_by_id`")


        collection_formats = {}

        path_params = {}
        if 'product_image_id' in params:
            path_params['product_image_id'] = params['product_image_id']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/product_images/{product_image_id}', 'DELETE',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type=None,
                                        auth_settings=auth_settings,
                                        async=params.get('async'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def get_product_image_data_by_id(self, product_image_id, **kwargs):
        """
        Get a single product_image data
        Returns the metadata for a single product image with a given ID. This method is useful for checking the status of an image after it was uploaded.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_product_image_data_by_id(product_image_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str product_image_id: Valid product ID. (required)
        :return: ImageResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.get_product_image_data_by_id_with_http_info(product_image_id, **kwargs)
        else:
            (data) = self.get_product_image_data_by_id_with_http_info(product_image_id, **kwargs)
            return data

    def get_product_image_data_by_id_with_http_info(self, product_image_id, **kwargs):
        """
        Get a single product_image data
        Returns the metadata for a single product image with a given ID. This method is useful for checking the status of an image after it was uploaded.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_product_image_data_by_id_with_http_info(product_image_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str product_image_id: Valid product ID. (required)
        :return: ImageResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['product_image_id']
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_product_image_data_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'product_image_id' is set
        if ('product_image_id' not in params) or (params['product_image_id'] is None):
            raise ValueError("Missing the required parameter `product_image_id` when calling `get_product_image_data_by_id`")


        collection_formats = {}

        path_params = {}
        if 'product_image_id' in params:
            path_params['product_image_id'] = params['product_image_id']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/product_images/{product_image_id}', 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ImageResponse',
                                        auth_settings=auth_settings,
                                        async=params.get('async'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def set_image_position(self, body, product_image_id, **kwargs):
        """
        Set image position
        Allows for changing the image position in the list
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.set_image_position(body, product_image_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param ImagePosition body:  (required)
        :param str product_image_id:  (required)
        :return: ImageResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.set_image_position_with_http_info(body, product_image_id, **kwargs)
        else:
            (data) = self.set_image_position_with_http_info(body, product_image_id, **kwargs)
            return data

    def set_image_position_with_http_info(self, body, product_image_id, **kwargs):
        """
        Set image position
        Allows for changing the image position in the list
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.set_image_position_with_http_info(body, product_image_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param ImagePosition body:  (required)
        :param str product_image_id:  (required)
        :return: ImageResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'product_image_id']
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method set_image_position" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params) or (params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `set_image_position`")
        # verify the required parameter 'product_image_id' is set
        if ('product_image_id' not in params) or (params['product_image_id'] is None):
            raise ValueError("Missing the required parameter `product_image_id` when calling `set_image_position`")


        collection_formats = {}

        path_params = {}
        if 'product_image_id' in params:
            path_params['product_image_id'] = params['product_image_id']

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api('/product_images/{product_image_id}', 'PUT',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='ImageResponse',
                                        auth_settings=auth_settings,
                                        async=params.get('async'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
