# coding: utf-8

"""
    API 2.0

    Early release of version 2.0 of the Vend API.

    OpenAPI spec version: 2.0
    Contact: api@vendhq.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PriceBookBase(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'customer_group_id': 'str',
        'valid_from': 'str',
        'valid_to': 'str',
        'restrict_to_platform_key': 'str',
        'outlet_id': 'str'
    }

    attribute_map = {
        'name': 'name',
        'customer_group_id': 'customer_group_id',
        'valid_from': 'valid_from',
        'valid_to': 'valid_to',
        'restrict_to_platform_key': 'restrict_to_platform_key',
        'outlet_id': 'outlet_id'
    }

    def __init__(self, name=None, customer_group_id=None, valid_from=None, valid_to=None, restrict_to_platform_key=None, outlet_id=None):
        """
        PriceBookBase - a model defined in Swagger
        """

        self._name = None
        self._customer_group_id = None
        self._valid_from = None
        self._valid_to = None
        self._restrict_to_platform_key = None
        self._outlet_id = None

        self.name = name
        self.customer_group_id = customer_group_id
        if valid_from is not None:
          self.valid_from = valid_from
        if valid_to is not None:
          self.valid_to = valid_to
        if restrict_to_platform_key is not None:
          self.restrict_to_platform_key = restrict_to_platform_key
        if outlet_id is not None:
          self.outlet_id = outlet_id

    @property
    def name(self):
        """
        Gets the name of this PriceBookBase.
        Price book name.

        :return: The name of this PriceBookBase.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this PriceBookBase.
        Price book name.

        :param name: The name of this PriceBookBase.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def customer_group_id(self):
        """
        Gets the customer_group_id of this PriceBookBase.
        The ID of the customer group

        :return: The customer_group_id of this PriceBookBase.
        :rtype: str
        """
        return self._customer_group_id

    @customer_group_id.setter
    def customer_group_id(self, customer_group_id):
        """
        Sets the customer_group_id of this PriceBookBase.
        The ID of the customer group

        :param customer_group_id: The customer_group_id of this PriceBookBase.
        :type: str
        """
        if customer_group_id is None:
            raise ValueError("Invalid value for `customer_group_id`, must not be `None`")

        self._customer_group_id = customer_group_id

    @property
    def valid_from(self):
        """
        Gets the valid_from of this PriceBookBase.
        The date when the price book becomes valid (active).

        :return: The valid_from of this PriceBookBase.
        :rtype: str
        """
        return self._valid_from

    @valid_from.setter
    def valid_from(self, valid_from):
        """
        Sets the valid_from of this PriceBookBase.
        The date when the price book becomes valid (active).

        :param valid_from: The valid_from of this PriceBookBase.
        :type: str
        """

        self._valid_from = valid_from

    @property
    def valid_to(self):
        """
        Gets the valid_to of this PriceBookBase.
        The date when the price book becomes invalid (inactive).

        :return: The valid_to of this PriceBookBase.
        :rtype: str
        """
        return self._valid_to

    @valid_to.setter
    def valid_to(self, valid_to):
        """
        Sets the valid_to of this PriceBookBase.
        The date when the price book becomes invalid (inactive).

        :param valid_to: The valid_to of this PriceBookBase.
        :type: str
        """

        self._valid_to = valid_to

    @property
    def restrict_to_platform_key(self):
        """
        Gets the restrict_to_platform_key of this PriceBookBase.
        `\"0\"` - all platforms, `\"1\"` - in store, `\"2\"` - ecommerce.

        :return: The restrict_to_platform_key of this PriceBookBase.
        :rtype: str
        """
        return self._restrict_to_platform_key

    @restrict_to_platform_key.setter
    def restrict_to_platform_key(self, restrict_to_platform_key):
        """
        Sets the restrict_to_platform_key of this PriceBookBase.
        `\"0\"` - all platforms, `\"1\"` - in store, `\"2\"` - ecommerce.

        :param restrict_to_platform_key: The restrict_to_platform_key of this PriceBookBase.
        :type: str
        """

        self._restrict_to_platform_key = restrict_to_platform_key

    @property
    def outlet_id(self):
        """
        Gets the outlet_id of this PriceBookBase.
        The ID of an outlet for which the price book should be used.

        :return: The outlet_id of this PriceBookBase.
        :rtype: str
        """
        return self._outlet_id

    @outlet_id.setter
    def outlet_id(self, outlet_id):
        """
        Sets the outlet_id of this PriceBookBase.
        The ID of an outlet for which the price book should be used.

        :param outlet_id: The outlet_id of this PriceBookBase.
        :type: str
        """

        self._outlet_id = outlet_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PriceBookBase):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
